# Generated by Django 4.1.1 on 2022-09-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_maindetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindetails',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
