# Generated by Django 4.1.1 on 2022-10-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_maindetails_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='empsignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('Mname', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=12, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
