# Generated by Django 4.1.1 on 2022-10-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_empsignup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empsignup',
            old_name='Mname',
            new_name='empMname',
        ),
        migrations.RenameField(
            model_name='empsignup',
            old_name='city',
            new_name='empcity',
        ),
        migrations.RenameField(
            model_name='empsignup',
            old_name='email',
            new_name='empemail',
        ),
        migrations.RenameField(
            model_name='empsignup',
            old_name='mobile',
            new_name='empmobile',
        ),
        migrations.RenameField(
            model_name='empsignup',
            old_name='name',
            new_name='empname',
        ),
        migrations.RenameField(
            model_name='empsignup',
            old_name='password',
            new_name='emppassword',
        ),
        migrations.RenameField(
            model_name='empsignup',
            old_name='pincode',
            new_name='emppincode',
        ),
        migrations.RenameField(
            model_name='empsignup',
            old_name='state',
            new_name='empstate',
        ),
    ]
