# Generated by Django 4.1.1 on 2022-10-07 10:18

from django.db import migrations, models
import proj.models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_rename_mname_empsignup_empmname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aimage', models.ImageField(blank=True, null=True, upload_to=proj.models.filepath)),
                ('heading', models.CharField(max_length=50)),
                ('subheading', models.CharField(max_length=50)),
                ('para', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Blo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('Bimage1', models.ImageField(blank=True, null=True, upload_to=proj.models.filepath)),
                ('Bimage2', models.ImageField(blank=True, null=True, upload_to=proj.models.filepath)),
                ('Bimage3', models.ImageField(blank=True, null=True, upload_to=proj.models.filepath)),
                ('Bimage4', models.ImageField(blank=True, null=True, upload_to=proj.models.filepath)),
                ('Bimage5', models.ImageField(blank=True, null=True, upload_to=proj.models.filepath)),
                ('Bimage6', models.ImageField(blank=True, null=True, upload_to=proj.models.filepath)),
                ('subhead1', models.CharField(max_length=50)),
                ('subhead2', models.CharField(max_length=50)),
                ('subhead3', models.CharField(max_length=50)),
                ('subhead4', models.CharField(max_length=50)),
                ('subhead5', models.CharField(max_length=50)),
                ('subhead6', models.CharField(max_length=50)),
                ('desc1', models.CharField(max_length=100)),
                ('desc2', models.CharField(max_length=100)),
                ('desc3', models.CharField(max_length=100)),
                ('desc4', models.CharField(max_length=100)),
                ('desc5', models.CharField(max_length=100)),
                ('desc6', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Defa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cdesc', models.CharField(max_length=300)),
                ('Ulinkhead1', models.CharField(max_length=30)),
                ('Ulinkhead2', models.CharField(max_length=30)),
                ('Ulinkhead3', models.CharField(max_length=30)),
                ('Ulinkhead4', models.CharField(max_length=30)),
                ('Ulinkhead5', models.CharField(max_length=30)),
                ('Ulink1', models.CharField(max_length=2048)),
                ('Ulink2', models.CharField(max_length=2048)),
                ('Ulink3', models.CharField(max_length=2048)),
                ('Ulink4', models.CharField(max_length=2048)),
                ('Ulink5', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Ele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainHead', models.CharField(max_length=50)),
                ('box1head', models.CharField(max_length=50)),
                ('box2head', models.CharField(max_length=50)),
                ('box3head', models.CharField(max_length=50)),
                ('box4head', models.CharField(max_length=50)),
                ('box1para', models.CharField(max_length=300)),
                ('box2para', models.CharField(max_length=300)),
                ('box3para', models.CharField(max_length=300)),
                ('box4para', models.CharField(max_length=300)),
                ('mainHead2', models.CharField(max_length=50)),
                ('Eimage', models.ImageField(blank=True, null=True, upload_to=proj.models.filepath)),
                ('prohead1', models.CharField(max_length=50)),
                ('prohead2', models.CharField(max_length=50)),
                ('prohead3', models.CharField(max_length=50)),
                ('prohead4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box1', models.CharField(max_length=50)),
                ('box2', models.CharField(max_length=50)),
                ('box3', models.CharField(max_length=50)),
                ('box4', models.CharField(max_length=50)),
            ],
        ),
    ]
