# Generated by Django 4.1.1 on 2022-10-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0006_abou_blo_defa_ele_hom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abou',
            new_name='About',
        ),
        migrations.RenameModel(
            old_name='Blo',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='Defa',
            new_name='Default',
        ),
        migrations.RenameModel(
            old_name='Ele',
            new_name='Elements',
        ),
        migrations.RenameModel(
            old_name='Hom',
            new_name='Home',
        ),
    ]
