# Generated by Django 4.1.1 on 2022-10-07 10:25

from django.db import migrations, models
import proj.models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0007_rename_abou_about_rename_blo_blog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('subheading', models.CharField(max_length=50)),
                ('ser1', models.CharField(max_length=100)),
                ('ser2', models.CharField(max_length=100)),
                ('ser3', models.CharField(max_length=100)),
                ('ser4', models.CharField(max_length=100)),
                ('ser5', models.CharField(max_length=100)),
                ('Simage', models.ImageField(blank=True, null=True, upload_to=proj.models.filepath)),
            ],
        ),
    ]
