# Generated by Django 4.1.1 on 2022-10-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0010_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='acceptemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=25)),
                ('empMname', models.CharField(max_length=25)),
                ('empmobile', models.CharField(max_length=12, unique=True)),
                ('empcity', models.CharField(max_length=50)),
                ('empstate', models.CharField(max_length=50)),
                ('emppincode', models.CharField(max_length=10)),
                ('empemail', models.CharField(max_length=50, unique=True)),
                ('emppassword', models.CharField(max_length=25)),
            ],
        ),
    ]
